import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/index'
import Footer from '@/components/Footer/index'
import Button from '@/components/Button/index'
import { useState } from 'react'


export default function Home() {
  const [itemOne, setItemOne] = useState(0);
  const [itemTwo, setItemTwo] = useState([]);
  const [position, setPosition] = useState({
    x: 0,
    y: 0
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className={`${styles.main} `}>
        <Button />
        <Button title='Click me' color="#ff00ff" />
        <Button title='Click me' color="rgba(255,255,0, 50)" />
        <button onClick={() => {
          setItemOne(itemOne + 1);
          console.log(itemOne);
        }}>Button 1 Number</button>

        <button onClick={() => {
          setItemTwo([...itemTwo, "testing"]);
          console.log(itemTwo);
        }}>Button 2 Array</button>

        <div 
          onPointerMove={e => {
          setPosition({ 
            x: e.clientX, 
            y: e.clientY 
          })
        }}
        
          style={{
            position: 'relative',
            width: '100vw',
            height: '50vh',
          }}
        ></div>

        <div
          style={{
            position: 'absolute',
            backgroundColor: 'red',
            borderRadius:'50%',
            transform: `translate(${position.x}px, ${position.styles}px)`,
            left:0,
            top:0,
            width:20,
            height:20


          }}>
        </div>
      </main>
      <Footer></Footer>
    </>
  )
}
